---
apiVersion: v1
kind: Namespace
metadata:
  name: web-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: web-app
  labels:
    app: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: hayder89/web-app:9
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
